Fix device test on VMs without keyboards
Fixes:

    test test_device_without_keys_is_not_selected_automatically ... FAILED

    failures:

    ---- test_device_without_keys_is_not_selected_automatically stdout ----
    Selecting devices from the following list:
    ------------------------------------------------------------------------------
    /dev/input/event0 : Power Button
    /dev/input/event1 : test device 0V60uKyscx
    ------------------------------------------------------------------------------
    Selected keyboards automatically since --device options weren't specified:
    ------------------------------------------------------------------------------
    Error: Failed to prepare input devices: No device was selected!